### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by BloodyBee** [LIQNFT/candy-shop-storefront-nextjs#1]
first off: 
kudos & chapeaux!

my problem: 
I'm trying to integrate this into an existing nextjs-project (that's based on the solana-labs/dapp-scaffold) 
and am weirdly getting a "ReferenceError: window is not defined" that I can't seem to find a fix for.

Do you have any idea or hint where this could be stemming from? I've been trying all day now to no avail.

`ReferenceError: window is not defined
    at /Users/.../node_modules/@google/model-viewer/dist/model-viewer-umd.js:572:20
    at /Users/.../node_modules/@google/model-viewer/dist/model-viewer-umd.js:2:68
    at Object.<anonymous> (/Users/.../node_modules/@google/model-viewer/dist/model-viewer-umd.js:5:2)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/.../node_modules/@liqnft/candy-shop/dist/index.es.js:7:366) {
  page: '/'`

**Comment by gonwi** [comment]
Hi @BloodyBee ,

You have to make sure of the 2 following things. 

- Wrapping `pages/_app.ts` with the `CandyShopDataValidator` ([See example](https://github.com/LIQNFT/candy-shop-storefront-nextjs/blob/master/pages/_app.tsx#L48
))
- Using dynamic imports for the CandyShopDataValidator and other candy shop components. ([Dynamic Import Example](https://github.com/LIQNFT/candy-shop-storefront-nextjs/blob/master/pages/_app.tsx#L29))

Hope that helps.

**Comment by BloodyBee** [comment]
Hi @gonwi, 

that does help massively indeed.

Thanks a lot!
